# ==================================================
# Tournament Routes
cerad_tourn:
  resource: "@CeradTournBundle/Resources/config/routing.yml"

# ==================================================
# FOSUserBundle Stuff
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /account

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /account/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /account/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /account/password-reset

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /account/profile
    
# ==================================================
# JanrainBundle Stuff
cerad_janrain:
    resource: "@CeradJanrainBundle/Resources/config/routing.yml"
    prefix: /account
    
# My own account stuff
cerad_account:
  resource: "@CeradAccountBundle/Resources/config/routing.yml"
  prefix: /account
  
# Redirect profile to home page
fos_user_profile_show:
  path: /home
  defaults:  { _controller: CeradTournBundle:Home:home }
